// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cockroach

import (
	"context"
	"github.com/sirupsen/logrus"
	"gorm.io/gorm"
)

// Injectors from service.wire.cdb.go:

func InitCDBService(ctx context.Context, logger *logrus.Logger, db *gorm.DB, interfaces DBInterfaces) (CDBService, error) {
	cdbService := CDBService{
		Db:         db,
		Logger:     logger,
		Context:    ctx,
		Interfaces: interfaces,
	}
	return cdbService, nil
}

func InitCDBRepo(ctx context.Context, logger *logrus.Logger, db *gorm.DB, interfaces DBInterfaces) (CDBRepo, error) {
	cdbRepo := CDBRepo{
		Db:         db,
		Logger:     logger,
		Context:    ctx,
		Interfaces: interfaces,
	}
	return cdbRepo, nil
}
